## Numpy Library

- Used for processing n dimensional arrays


In [1]:
import numpy as np
li = [1,2,3]

a = np.array(li)
a

array([1, 2, 3])

In [4]:
import numpy as np
li = [1,2,3,'a']
a = np.array(li)
a
b = np.arange(15)
b

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

## Generate n random numbers

In [7]:
rn = np.random.randint(10,20,size=10)
rn

array([13, 17, 16, 19, 10, 14, 18, 15, 12, 18])

In [17]:
rn2 = np.random.randint(0,2,size=(3,3))
rn2

array([[0, 0, 1],
       [1, 1, 1],
       [0, 1, 0]])

In [18]:
rn2[0][2]

1

In [24]:
rn3 = np.random.randint(0,2,size=(3,3,3,3))
rn3
rn3[2][2][2][1]

1

In [27]:
rn3.ndim
rn3.size
rn3.shape

(3, 3, 3, 3)

In [28]:
rn3.dtype

dtype('int32')

In [29]:
rn3.itemsize

4

In [30]:
rn3.nbytes

324

In [32]:
rn3[2, -1]

array([[1, 0, 1],
       [0, 0, 0],
       [1, 1, 0]])

In [33]:
print(rn3)

[[[[0 0 1]
   [1 0 1]
   [0 1 0]]

  [[1 1 0]
   [1 1 1]
   [0 0 0]]

  [[0 1 1]
   [1 1 0]
   [1 0 0]]]


 [[[0 1 0]
   [0 1 0]
   [1 0 0]]

  [[0 0 0]
   [0 0 1]
   [1 0 0]]

  [[1 1 1]
   [1 1 1]
   [1 1 0]]]


 [[[1 0 1]
   [1 1 1]
   [1 0 1]]

  [[0 0 1]
   [1 0 1]
   [1 1 1]]

  [[1 0 1]
   [0 0 0]
   [1 1 0]]]]


## Pandas

- Use Cases
    - Data Analysis
    - Data Cleaning
    - Data Transformation

- Notations
    - Series ->Row(1D representation of data)
    - DataFrame ->Table(2D representation of data)

In [39]:
import pandas as pd

internal1 = {'s1':21, 's2':18, 's3':24}

internal1 = pd.Series(internal1)

internal2 = {'s1':15, 's2':19, 's3':14}

internal2 = pd.Series(internal2)

internal2


s1    15
s2    19
s3    14
dtype: int64

In [40]:
final = {'Internal1':internal1,'Internal2':internal2}

final = pd.DataFrame(final)
final

Internal1  Internal2
s1         21         15
s2         18         19
s3         24         14

In [41]:
final["Internal1"]

s1    21
s2    18
s3    24
Name: Internal1, dtype: int64

In [42]:
final.columns # Name of all columns

Index(['Internal1', 'Internal2'], dtype='object')

In [44]:
final.values # List of all rows

array([[21, 15],
       [18, 19],
       [24, 14]], dtype=int64)

In [45]:
final.values[2]

array([24, 14], dtype=int64)

In [46]:
final.values[2][1]

14

In [47]:
for row in final.values:
    print('Internal1 -',row[0],', Internal2 - ',row[1])

Internal1 - 21 , Internal2 -  15
Internal1 - 18 , Internal2 -  19
Internal1 - 24 , Internal2 -  14


In [53]:
final.loc['s4'] = [16,20]
final

Internal1  Internal2
s1         21         15
s2         18         19
s3         15         18
3          15         18
s4         16         20

In [54]:
final.drop(3)

Internal1  Internal2
s1         21         15
s2         18         19
s3         15         18
s4         16         20

In [56]:
final.values[2] = [12,25]
final
final.drop(3)

Internal1  Internal2
s1         21         15
s2         18         19
s3         12         25
s4         16         20

In [58]:
final.drop(3)

Internal1  Internal2
s1         21         15
s2         18         19
s3         12         25
s4         16         20

In [59]:
# Reading CSV file data
import pandas as pd
filepath = 'DataFiles\Income.csv'
incomepdf = pd.read_csv(filepath)
incomepdf

GEOID       State   2005   2006   2007   2008   2009   2010   2011  \
0  04000US01     Alabama  37150  37952  42212  44476  39980  40933  42590   
1  04000US02      Alaska  55891  56418  62993  63989  61604  57848  57431   
2  04000US04     Arizona  45245  46657  47215  46914  45739  46896  48621   
3  04000US05    Arkansas  36658  37057  40795  39586  36538  38587  41302   
4  04000US06  California  51755  55319  55734  57014  56134  54283  53367   

    2012   2013  
0  43464  41381  
1  63648  61137  
2  47044  50602  
3  39018  39919  
4  57020  57528

In [64]:
# Extract income of all states in 2013.
incomepdf.values
for row in incomepdf.values:
    print(row[1],":",row[-1])

Alabama : 41381
Alaska : 61137
Arizona : 50602
Arkansas : 39919
California : 57528


In [66]:
# Average income of Arizona
sum=0
for i in range(2,11):
    sum+=incomepdf.values[2][i]
sum/len(incomepdf.values[2][2:])

47214.77777777778

In [69]:
# Average of all income of all states in 2011.
sum = 0
for row in incomepdf.values:
    sum+=row[-2]
a= sum/len(incomepdf.values)
print(a)

50038.8
